#!/bin/bash

CWD=`pwd`

if [ -e $PWD/sources/poky ]; then
    OEROOT=$PWD/sources/poky
elif [ -e $PWD/sources/oe-core ]; then
    OEROOT=$PWD/sources/oe-core
else
   echo "Cannot find OE-Core! Aborting..."
   false
fi

. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null

# if conf/local.conf not generated, no need to go further
if [ ! -e conf/local.conf ]; then
    clean_up && return 1
fi

cat <<EOF >> $PWD/conf/local.conf

MACHINE = "rock-5b-plus"
# MACHINE = "radxa-zero-3e-custom"
# MACHINE = "luckfox-lyra-plus"
DISTRO = "beaveros"
INHERIT += "rm_work"

TMPDIR = "/mnt/storage/beaveros"
# DL_DIR ?= "/mnt/storage/yocto/downloads/"
# SSTATE_DIR ?= "/mnt/storage/yocto/sstate-cache/"
BB_GENERATE_MIRROR_TARBALLS = "1"
BB_HASHSERVE_DB_DIR = "\${SSTATE_DIR}"
# INHERIT += "buildhistory"
# BUILDHISTORY_COMMIT = "1"

EOF

LAYERS=" \
    $CWD/sources/meta-openembedded/meta-oe \
    $CWD/sources/meta-arm/meta-arm-toolchain \
    $CWD/sources/meta-arm/meta-arm \
    $CWD/sources/meta-rockchip \
    $CWD/sources/meta-openembedded/meta-python \
    $CWD/sources/meta-openembedded/meta-networking \
    $CWD/sources/meta-openembedded/meta-gnome \
    $CWD/sources/meta-swupdate \
    $CWD/sources/meta-openembedded/meta-filesystems \
    $CWD/sources/meta-clang \
    $CWD/sources/meta-radxa \
    $CWD/sources/meta-beaver \
"

for layer in $LAYERS; do
    layer_name=`basename $layer`
    echo "Adding layer $layer_name"
    bitbake-layers add-layer $layer > /dev/null 2>&1
done

echo "To start building, run 'bitbake lab-image-minimal-update'"